{
 "title": "Probing Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "benchmark_id",
    "label": "Benchmark ID",
    "query": {
     "query": "SHOW TAG VALUES FROM \"benchmark_metrics\" WITH KEY = \"benchmark_id\" WHERE $range"
    }
   },
   {
    "name": "benchmark_start_time",
    "query": {
     "query": "SELECT benchmark_started \nFROM benchmark_meta \nWHERE benchmark_id ='$benchmark_id'\nLIMIT 1"
    }
   },
   {
    "name": "benchmark_end_time",
    "query": {
     "query": "SELECT benchmark_finished\nFROM benchmark_meta \nWHERE benchmark_id = '$benchmark_id'\nLIMIT 1"
    }
   },
   {
    "name": "benchmark_selected_name",
    "label": "Configuration",
    "query": {
     "query": "SELECT benchmark_name\nFROM benchmark_meta \nWHERE benchmark_id = '$benchmark_id'\nLIMIT 1"
    }
   },
   {
    "name": "Scheduler",
    "query": {
     "query": "SELECT used_scheduler\nFROM benchmark_meta \nWHERE benchmark_id = '$benchmark_id'\nLIMIT 1"
    }
   },
   {
    "name": "range",
    "label": "Since",
    "query": "today : time > now() - 1d, last_2d : time > now() - 2d, forever : 1=1"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average IPC",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_instructions_per_cycle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Cache Misses",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_cache_misses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Instructions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_instructions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Maximum LLC Occupancy (%)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       {
        "params": [
         "rdt_cache_llc_utilization_percent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Memory Usage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "docker_memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Instructions Per Cycle",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_instructions_per_cycle" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Misses Rate (%)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_cache_miss_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Total Instructions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_instructions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Mean IPC",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_instructions_per_cycle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Mean Cache Miss Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_cache_miss_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Stalled Cycles (%)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_stalled_cycles_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Cycles",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_cycles" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Stalls",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_index::tag" ], "type": "tag" },
      { "params": [ "container_name::tag" ], "type": "tag" }
     ],
     "measurement": "benchmark_metrics",
     "select": [
      [
       { "params": [ "perf_stalls_total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Benchmark Info",
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "options": {
      "content": "## Benchmark Run {{benchmark_id}}\n### General\n**Name:** {{benchmark_name}}  \n**Description:** {{description}}  \n**Time:** {{formatDuration duration_seconds}} ({{formatTs benchmark_started}} to {{formatTs benchmark_finished}})   \n**Containers:** {{total_containers}}  \n**Driver:** v{{driver_version}}   \n**Scheduler:** {{used_scheduler}} (v{{scheduler_version}})    \n\n### Host\n**Hostname:** {{hostname}} (exec host: {{execution_host}})  \n**OS/Kernel:** {{os_info}}  {{kernel_version}}  \n**CPU:** {{cpu_vendor}} {{cpu_model}} {{total_cpu_cores}} cores / {{cpu_threads}} threads   \n**L3 Bytes:** {{toMb l3_cache_size_bytes}} MB   \n\n### Sampling\n**Limits:** max {{max_duration_seconds}} s    \n**Sampling Rate:** every {{sampling_frequency_ms}} ms    \n**Volume:** steps {{total_sampling_steps}}, measurements {{total_measurements}}, data {{formatBytes total_data_size_bytes}}\n\n---\n\n### Configuration\n```yaml\n{{{newline config_file}}}\n"
     },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "benchmark_meta",
       "query": "SELECT * FROM \"benchmark_meta\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) ORDER BY time DESC ",
       "select": [
        [
         { "params": [ "hostname" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Probe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inference Sensitivity",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "alias": " $tag_container_name - CPU Float",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "cpu_float" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      },
      {
       "alias": " $tag_container_name - CPU Integer",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "cpu_integer" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      },
      {
       "alias": " $tag_container_name - LLC",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "llc" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      },
      {
       "alias": " $tag_container_name - Memory Read",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "mem_read" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      },
      {
       "alias": " $tag_container_name - Memory Write",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "mem_write" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      },
      {
       "alias": " $tag_container_name - Network Read",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "network_read" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      },
      {
       "alias": " $tag_container_name - Network Write",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "network_write" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      },
      {
       "alias": " $tag_container_name - Pipeline",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "scoreboard" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      },
      {
       "alias": " $tag_container_name - Storebuffer",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "store_buffer" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      },
      {
       "alias": " $tag_container_name - Syscall",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_probes",
       "query": "SELECT \"cpu_float\" FROM \"benchmark_probes\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag, \"container_name\"::tag",
       "select": [
        [
         { "params": [ "syscall" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "docker_cpu_usage_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Instructions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_instructions" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Instructions per Cycle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "container_image::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_instructions_per_cycle" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "MIP/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT non_negative_derivative(mean(\"perf_instructions\"), 1s) / 1000000 AS \"MIP/s\"\nFROM \"benchmark_metrics\"\nWHERE (\"benchmark_id\" =~ /^$benchmark_id$/) AND $timeFilter\nGROUP BY time(1s), \"container_index\", \"container_name\" fill(null)\n",
       "select": [
        [
         { "params": [ "perf_instructions" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "container_image::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_cycles" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Stalls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stalled Cycles (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_stalled_cycles_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Stalled Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_stalls_total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Stalled Cycles",
     "type": "timeseries",
     "description": "Execution stalls while memory subsystem has an outstanding load",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_stalls_mem_any" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 231 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_cycles" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "L1D Stalled Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 239 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_stalls_l1d_miss" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "L3 Stalled Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 239 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_stalls_l3_miss" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "L2 Stalled Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_stalls_l2_miss" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Scoreboard Stalled Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 248 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         {
          "params": [
           "perf_resource_stalls_scoreboard"
          ],
          "type": "field"
         }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "Store Buffer Stalled Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "perf_resource_stalls_sb" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RDT Allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "LLC Allocation (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 400 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "container_image::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "rdt_l3_cache_allocation_pct" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "RDT Cache Allocation Group",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 400 },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "container_image::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "rdt_class_name" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    },
    {
     "title": "LLC Allocation (Ways)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 408 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "container_index::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "container_image::tag" ], "type": "tag" }
       ],
       "measurement": "benchmark_metrics",
       "query": "SELECT \"docker_cpu_usage_percent\" FROM \"benchmark_metrics\" WHERE (\"benchmark_id\"::tag =~ /^$benchmark_id$/) AND $timeFilter GROUP BY \"container_index\"::tag",
       "select": [
        [
         { "params": [ "rdt_l3_cache_allocation" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "benchmark_id::tag", "operator": "=~", "value": "/^$benchmark_id$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}