version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: rdt4nn-influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE
      - DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_RETENTION
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
    expose:
      - "8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - net
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  influxdb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${INFLUX_DATA_PATH}
    external: false
  influxdb_config:
    driver: local

networks:
  net:
    external: true
